Lint/NestedMethodDefinition:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Metrics/LineLength:
  AllowURI: true
  Max: 93 # TODO: Lower to 80

Metrics/MethodLength:
  CountComments: false
  Max: 21 # TODO: Lower to 15

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/ClassVars:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    map:      'collect'
    map!:     'collect!'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingComma:
  EnforcedStyleForMultiline: 'comma'
