inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"

# Standard Ruby compatibility
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/SpecFilePathFormat:
  Enabled: false
