bundler_args: --without development
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  include:
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  fast_finish: true
sudo: false
